import PageHeader from "@/components/PageHeader";
import { InfoOutlineIcon } from "@chakra-ui/icons";
import { Avatar, Box, Card, CardBody, CardHeader, Center, Code, Container, Divider, Heading, HStack, Link, ListItem, Text, UnorderedList, VStack } from "@chakra-ui/react";
import Head from "next/head"

const About = () => {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by Harshith HM" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="main">
        <PageHeader />
        <Box mx={[2, 2, '20%']} my={[6, 20]}>
          <Heading mt={[10, 6]}>
            <Avatar src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAACNFBMVEUAAABBN3g/Nnk/Nnk/Nnk8NXk/Nno9Nno/Nnk6MnY+Nnk/Nnk/Nnk/Nnk9NXk/Nnk8Nno/Nnk/NXk+N3c/Nnk/Nno+Nnk/Nnk/NXk/NXk/Nnk/NXk/Nng/Nnk/Nnk/Nnk/Nng/Nnk/Nnk+Nnk/Nng/Nnk/Nng+Nnk/Nng/Nnk+Nno+NnnOzs4/Nnn4ryNwcHBjvOfi4uKvr6/4cCNj4udbW1u7usNJQH/ExMhSSoTb297V1dWzs7NybZGem7FCOHdjw+dpaHFYRm1XkMNGUY9ETYjMy9Tgny5DPHREPHhGPX1uVWN7XV2edEz4pCO7hz/4fiNSQXBWTodRS3ZIP3JST2RhXnNvbnDaZjH1qiRVUHVfX1/KkDmsqb6Df6FNRYBeQGvY2NtGWI9KQYDYmjLqpilLbaBlZWVZWF2np6tZVXRi2+ZdWnNra2uDYllgTGnCizxHOXX4nCNtbHFIQXegn6hKY51BPoBLOXNLRmytfkXuqSf4dyPIx8l5c5u2hELsbChLRXd2Wl96SF2LZ1aXb1CyWUPPlDZUiLmXlK9eWIvAXz1oUWVqQ2VWVGGmeUnmoyuzscFkYnKRa1OkobhuaJbzbiX4hyOMiKlmX5JNR3acVE7kaS1iuORfrtxmZHJVPW+pV0jSZDRcpNRamsxOSmmITVeTUVLBwMNOdqpJXJfJYTmRjKtESYf4jSPS0tJSfrRizuaYl6T4kyPU09lYrsa7u7u4uLiOi59oYo1jYHJdxdS0msQGAAAALHRSTlMAM97M9yJ1EKwGxIHw2SfqCh1rF9KqXpksSqCSQOY6u4yHTrFkRVNYeqVwtuZ2zMEAACLhSURBVHja7N1LbxJRFAfwK0xFpZRWG6sI0vp+5HAXhDXBlcT4Ci9FFy5MJA2aKGyIbqoLV6LRhYmaYEzQhUt3fjodZuAMziD1cWfuNP/fph/g/ueccw8wFQAAAAAAAAAAAAAAAAAAAADBi+06tv/MkbPns9loNLovm92ztnHuYHpFwI4XS59LRRfJmxE5vnF6ScAOtXQilaD5FrPxk8sCdpblk0citH3Gvt27BOwUsYPnDfpjkQ1kYEc4dtygv5SIYzAMuYV4hjxcrPZ6w9pP/Z/Mv81mpVsmD+ePCQito3s8jn5YaxWcbt27Ly2dQbu5VXS1gnMxAWF0at+vh98bnz27ZZ8+G7QrZZqyuH5AQNgcjpJTscqH73j4G9JLY7DZJSdjHVUgXNLRqdPv1QqMj1/+Rmk6A4tx7AbCYyU1Vfn59Kdr/zylZplY5oSAUFjeMIj1+n98/KzR3iIWxWIgDNIJR+0ftv7u+NmgQmwNo4DuYqnZtZ97/x8pOSIQOSxAZ+kIP/21giee/P8qAmsYBjUWd/T+VuEfq7/Ta54FEpgEdLXAd79q6z89/jwOlslm7Bego3TSVf3//fFnHe4DZ9EGNHRmRvVntxryn3wvk211QYBe9qZmPP6Mh/9/LwLJtACdxPZx91dQ/ifqRbIYpwXoYyVBtmFBRflnpS7ZdgvQxUKEy7+a82eNCtk2BOhhKTNe/bUUtH+XTbKtC9DBoSS3f5Xn7x4E1gQEb/L89wpqz58NyqgB2liJ8Pin+PxZaZyAuIBgHfD1/N2XgXMCgrQcJUvNl/NnnXECTgkI0B6fn393AoyjAgKzzuev6P4/fw5I4tdDgTnN87/v588JiO4VEIilRRqpFphr/6/QoEgjKQFBiCX4/L3dl2rVyYIvjAfiLO9/fR0A3VthA68VCcApsvRnNgCpXoVGVjEG+G7FHgBqAQyArNHFTjggWb4A+D8AsJI9CGIb4LMTwQ8AljaNJNAEfHVgcd4A0JA+qeBjIb/xCngYWANgnTKZjEMCfJO2G0AhsAbg3gZkBfhmVZsG4GgCeJ2Ub/bTSE+LAjD5UCCCOdAny0kyFVvBrIDcNvHlEF+doZGaBhOgpWGVgCReH+GLWNKeAHUpAJM58IwAH8R1KwA/baEE+IMngKpGBUDK1/i5mD/4CtDXqQCMS0AGFwH1IhoWgEkJOChAsVMaTgBcAlYFKJbV7gpgqeNjYV8s2AVAkyWgQxdfEPXDBpmKhZkaMgC8DjRwE1Qro9WnAE4dGsE75JQ6qeUd0Pmh4D4BCq1peQecugniv4sotDep6whoKqMHqHaYRlo6dgApm+gBqh3RuANMegDuAeokdO4A4x6AV0gqs6R1B5Cygl2QWvt5DexNBofXwRkBiuwhU0/TEWCyC8JvhVXJ6D0CSLmF1wWotKD5CCBlE0OASqetEUDDD4Kmh4CEACXWNR8BpOxgE6BS1hoBNA6ALONbIQolydTXdwaU8h2mQHUO0EhB3xlw/K2QIwIUSFszoNYBqOOX4uocJFNV2z2gaYBrgDpx7S8B42uAIUCBlP6XACmLZML7o1XI6r4INnVxD1RmVf9boJTv8LYYZTJkaukdgAoWAcoYYQhAEz8TV2WZRgp6B2AT/1RUBV4EFrXeA0nZxipQlZUQBQD/UlSBhRmb4FaPir2WXgHAV0IUWJoRgKr1b8O1CsBZAf/dIe8AtMhS7WsRgDqZ9gjwKwA1GquUZPAQAKY4ANwBdIoAAsB8CUCLnIrNjvwjCEB4eAdgSCZ9qgACwHwJwEUy3XlIrDKQ24YAhIdnAPo08unDZ3LothtyexCA8OAAuDrAx3w+f+PZ9DCwvU6AAIQHB8DVAb7kTV9fkNO77ZQBBCA8OADuDpAfefv8EjmVK3U5BwIQHl4BGFojYN7yLZe7fYmmlOe0AgQgPMYBcHeA93nLo9xPd988/DUD32f3AgQgPMYBcHeAG3nLldzI45fXyca9YEYGEIDw8AhAjzuAKTd28+pT+lWlXZJuCEB4cABmdIAnOYdXly/Qr8ruECAA4WEHwN0BPuQt13LTbj+o0rwQIADhwQGY7gAv8ra3OeaRAVbc2qzbKUAAfrB3N79JpHEcwMcWrcXiqtututp9666v+T4X/oCJXKoBtk7K7nYMhx4g2RjDi+uhAROQQjlAUyJJm6jJth7aQxMv3vav2z4D7WPLjMwzMDCT/D6nhsNc5tt5fs+7f/QGQAW3F+76xEzoS7EEzDxZfv7fPxQA35i+felsAP4QLYDhMzOnJ9sRmHvy5tmLt0OMwT9vn4GbvUu7A4fql4sBdDw2bQEML5m11FZUhRX11fKzF/89ct5T/OvR2xfPn717BQihS5SBYZkL4cRj0xZABMBaMVlrqhDMgvBu+dnzF2//5Vno/9Ifvf3z6LUvv3mlwlTge4rAMNwIAsLj3hZABKCvYo6HwA71yas375aXl58ded7F/z766c2bV0+ewI4Z2iM4uLkAzAMgWgAxEGiHXi9kshiRh3Ri3IAe4LTHZ1qADZkACMX6Viarwn2zdIPMQC7gWH4T3OPTLYBalg6AoKdy8UwzgeFJZLPgIhEcC1EhMIBf0bW6sb0iAiBagPWw0wAIrWShlolGVDimas1Ye2splWZsCVyMpaoqOmavKMShcwEY8rzUFwEwaQFEAJxLp3JHSYhFs1oCNiQizUqmHS/lUi12TASAscUoQDtFBzI9C8PuSlgEwLIFEAEYnJ5O1XNLpUKhEI/Ha7Vatdqu1Y7+PPqhtLSUrKdaRWZGBICrAXRgzCCuwbD7IdwbgIRoAUQAPEAE4EgchnlqBAa5JDC/Eu4NwN8wbHg7AKwKwwOFODAnXnJPAP4Aly97PADFCLgJhTgQBLcZ7g2AaAE8HgCWg+G2QpweDt7oCYBoARqeDwDL0plBTt0BtxvuCYBoAba9H4ACuFmFOLwgZv1sAP7mjlsA7wdgEQbqB8i7eKbOX8FZDR8EgGngbihE1iS4hnUA1rb9EIAmuJsKcXY29EfrAOyH/RCAGLg7Chl6AA59EYAKBcChYJ8mYDPsiwA0wf2mEFn3we2dDcBax+5+2R8B0Og+aYcumXYDV8MnfBGAFLjAtEJk3eyW+v4OQBxcUCHSpgLgNnwdAF0Dd0kh8hbA7W7LB2DRTJrZp5s/QT4AJRjOKUTeLzC8lw1APA9T2TqzqW31hJRkANIauEmFOBECpx7KBaAAK1qR2bIFKxFdKgB6BYa7CnE+H4i1j1IBqMBSjtnShKW6VAAyoLnAIVQBWGvIBCDm8PUJUVhKSQQgXQHoGsmBTE2gY79sPwBJWMnqzJYcrEQlaoCcBtAVYgO6HUBH/mDFdhGYi0bMZKtpZtOSxRPaRbsBKJaaAOgu+YHdCeCY5qNxgISKY5O0PXQgN0UCfBQAIUjvf0A/TPg5AD/TJMDApq77NgAhqv+H4tyCLwMw/4CWgg7L+UuzPglACR0z392hr/9QTd0Ft+uLAPxIq4CHb8oXASjQTiDXgFsLW3rJPKBA8/+uCeCIKhGAxVpWy0cySSZPPCGRj1TrzLY47Qd3zTy4su0AxFV0xNLMmZqKjkyR2dQGR+cDuiEE7kPYymd2SgYnIs4SEMOJrN0EZGgbgGsmxU4RU5+sV3VEmQNxQKgweyq0DcA1D8VOEVM77AvpBL60xKQtqk4Wk2RpDaBrbomdIqaefmVZV9ThB0CIMVsS4GgGyA0PwB2Erbzu+RQLqs5kNXFKgtmRBveNQlxwU2wVMtf7KRYWmSwNp6WZDSnaB+Key30nA8YfgBK4+wpxwTQM27YGAqLDbgLyzI4aDQS6aKJPP/Czm0VgRaIXOKcQNyyA27DVD2zl8aUSM6VvRTOpYXYDNeoFuugeuH173YA4IDS/Mm6nWiWgLf8JaYELKMQVv/WrAnWLgVyt9bX3lWHm9Kj0YPISdQLcNAWZ6SAxlRNtMXPJr/9z61V0VdLMljbtBHHVbJ/B4E/slFQ1okKL5RiTDoB4AqBlcsymLN0P4KrrfcYCn7IeOhPkAiCeYFsaBronyi1z/YoAJkEEYMgLAkMKccm36LMk4OV4A5ChBYEuC/aZENwZbwA0WgzgsnviiEhTr8cWAPG4GdoP4J4b/dqA38cZgCrNBLku1KcN+DTGAOgaHQjkulv92oAxBiAHLkCrgdx0DoYV+X6A+wGIgVtQiJtm+4wF7YwtAGmVhgFH4Jo4QdicPq4AxMHNK8RN4gRhK5+ZffUhBIBOBR6x++BWh1IGpsG1h3kwwHmFuOs2DI2hlIE1AIlFNgxZOhNuRGb79ASfMglL1XiLDUOSbooflbswHHrroIgonQo8MiHpT4D7cnQs+OjMwdDw0lEhWVoJMDrTE+BWt73zCSiB9gOM0DUY9jzzCShq4CZoIng0pkPg1soSYwGuilMFMFo3YdiXGA5002KetgOM2MM+XcHXOhuhKF0NNmrnA33qwB02OiUYritkdH6C4b0H6sCWBm6GdgOM0tQ8DIfjrwOjoLMhx+A3GHbLfVYHum4LVAGOxXUY1sfcCKRUcAGaBh61KxMw7I21J5COwHBNIaP2AwzqoeyIcLpeZKZSKSarQlfDjc9PMOx+kCsD4irUAuvVagLZRSalBsPMVYWM3nQQhtWyTBlQB7fV+/4j8usDS+i4qZBx+HYehvVtqzLgd8tx+7Z+JhcaOJVJSKow3FPIePwQgGFfohAsoCObZEK6rcKgMftSCRguKmRc5tBxYL8QLEbQ1Sy0GKcnqwl0FZhtixoMIdoLNkbX0WdMeMfqxRm0aCWazeNETf79z1xWyPhMLzhIQAQW4swm8ZAAXQ46XleC6Diw3xksxmAmkXPw/qkDMG5Tk/IJYCUNPTJpifpPAy0C8oqpEPr0BnfMDgmO4EtqLMXsq2ugKUDvuDqBjs2yzPKQZDuLjkSlkGYSSio6LijEC66e3Cy9IrdASE8lc7l6S34JKM0AectUEB35htV4gM6GQ1SQAdoF4B1XHqLrvcSosBOpCKj+96Dp++ja/GCRgJdsCAp5dMxQ/99jLqArv+HaIrF0BV2hGwrxmF9m0LX+wZ1CQIweLND4vwddDqFrbcOFZqAVwxG6EcLDphZwbPPjkDeM6PE8umao/POsawEc2y8P8yOwFMGxIC0A9rDLQRxbe28egR2dyUo2cSxAo78edyHQLwKvPzMp9ShOBGn23/NuTEJE4ODDoO1ArokTAVr95wtz8zih7puWg0/tRSBdiEC4T6u/fWLq5wCE1b2yswgkM3kIkzT25yPnLwKCur5Rlq0F6m0NEOZp6sdnzl3E6QzsrfRG4JPOzBRz1Qi+NHHtikL85vL3AZyyu7+x0rclKObiURWnhH6l47/86eqtAM5Y2zzY+Fg+9RnY6WZAX8zFM1mcNUnr/nzsyq9BmFhbXd8/2NtoNBqHh43Gxt77aiaqwcTMLTr66X/27vTHxSCOA/ijfajaHuyuqyxr17r2+aquxH3EEVLHC0tcoYgjIeKIM45130QWK+sWxC1ERPDXMfM8Ots+M22fUqbzzOelbCW7/T7zzPmbahcbFUeZ+o3Wr34VhOGJXvRTDjzT178oBdTpdw/OHUVRK5bd3LZcB0ApoCb/cvfZxQfnNs8F14ql52/uoycEdADUwgJgu/vw2bVjy8+f37Ps7NKly5btOX/75qkN25zKQToA6gFVtIKUDoCqdAB8TgfA53QAfE4HwOd0AHxOB8DndAD8Lew9AHoxSB39JwRA3fUaAAzUmwGqXmhCAxwPSg7A9hVw9FPqOvCm5laf7W2tq4mAeVdqAM6CCarzJxvrt8JWvfO2BD49XVoAbiJH/SBF9oQGACBu+MWQhIk850oKwLa5yBOYoMLWsKEgTMMfBjQDzME0qIvuAAjLiZ+ZCyY+2qh6zX663iwcBXPmR3I1qP1riwdgj/OhNQd2pUEocjV8nanG7+GluaPuP0n+sh7sstmCATgFau68Xx9awyKAoFHlxoGIqPAyK8EYOFbOS1JrDoJ6WSQAi1eBWu18bPdB2OqNKhcFMczwh16g1tOvn5oH27WCAVh33clN9nNrVtsRaDaqW4u/rjjvD+pAktkN6ujDQgG4ACrd84PrlZgXHqjGi6xkARC3kj2sBHWjQAA2wPYk2cN9FTpPIROEAoOZUoR71QZA7E72cCAN6gELgGAKeFeyJ/tjg5uq+n74PiBMHxS4DDUN62fCsT7Z0y1Qc5+JAnAW1P1kTm7wW2BgbdXWiIraKTYUN6Im++Wzr5LZxaaEeQE4Bio9zxUbpmH8oGp8iob7oAsYbhnWgDzpZI41Z0Cd4wZg236wESCzG/mCNVXXEIxXYyhbwPBEBBwHkjnmzQV1kROAdXtdrw1qPTiCE6qqRxAy1b7iJDYqAL5byRxsStgdgPOgDq5J5roPLrN1TPUsEk5QugvY1Ip8S+5lrrJhAG8seMJVEBJsCpgzCOjuaEe+hppqKRxYDyJhKCjUJ4Bc0zved1qWleG152xK+FV+MfhV4CfmAKgZqdSXzu57aeQw+1ZFt2oEKAULHYZq4shxNdNp2a7kDgNcU8J514QuZVPAuZ6AaE/ZZnRmNoGqpk1jCRBRQzV1jSbApLuuvLayOtkwgDsWXLGdswuUTgHzBgFdKWZKdzt6Csp+f0DIVPKWy/59IgDT3j3N6ukkGwbwe3VLJzKX5rI+I3cQ0J3KMS0zFWD6DTdkVqtiFzBcGwezKdvyM9NzZvU5U8I3XZuAdiVFcbmTyjPjzj2AaZZ5ZiAIYryhkpYomPYrFse9nE4db0p4m2sTUNItDWJaym1RZgmyzEZpH7BeoORupbwZkABz9Y7Fw4YBomYd84+7NgG5rAFlpXi+vN+KrAZZV9oGy94F7F/X25taE1lX50wR6AZxZh5PGtSexcSl/aB28X5yNYhNv/6/RTzTerYCid7eDPgnjUb/iLwXXfcfOqo1AD+LBBOVXmEcDcKUb+o63NTXhAYgWtPbqJwgiIGGZMK1/n7084wfYlTIEFAthlyGR6HlSISMihgGImBIJTQeWr6GijykThdQruvOhkTRU3rqJrfpyml3mb618sWpB4EwpVq2HBHBb0u+Zz7vbHOZddJS0BbeZFJn91VkjQ8bf1s/+Q41DDfhaM+0cX211PQxxfBnFJv/dgJioGRaruoVgW3Ttza+15ayUnxfMnAk/qy9H1abl6DGEruALcPG1Rn/RF0DbLPbBKZZCpuR4psyHfjj3lorgGBOAsLx0joXfQDEexv/wkjYMm3+e/6JlMCXe6DM8tdsmtwnmMaCKtYFHGD+s0MDtaDSv5p/f73/WT9AYEYXqED/8hsAosZdE6K1tJPjI43Kq4uAEn7/syzVzRQm4N6fXVXVG1TODrUI+6fiBykbjcobDKqjTUTJ8Z+rG8D3ZdMfjdlrQMTDrkxE5Dk5PsAE0d7m1xcAlRLphOcaDuLHmAWgXp6T46NApD/7uQEgE0IiHX+wea8JVCznjes0KdKcHA+A+O7vBoD0AwUWgRr912qARUEEY5KcHG8BdcjfDQDpBYh0lF3JbQCosa6lQCoeHDg2/P9PjjeCuNrm3yEAGwjwTRE/jN67gKw0HBUf899PjgdBZHz+BiDvAKHp5U7dB/j9xwkA0/ifT46HTecN4NNJQCZV5B1QU25dxCG8/SDMhP97cjwGYmub37sAhToBd8o8w9FX2HkYFEGW2fu/nhxvYl0APssvthTpBAT/ZhnYuj7BCByJ/3pyfBCI7zoA1swiA8HA3y4DG2qpt3/iv54crwUxWwegQAC+gIj/5RpgrI3o9T9PjvexA+D7UWChAMwAYVagDGwriBZPXUAdAJv0ARhfQs+hnx0ATyfHdQBssgeglMn8AaB6ezo5rgNgkz0ApUzm14AIeDo5rgPgkD0ArAtYdLHY28lxHQCb5AEoZTJ/KKiYp5PjOgAOyQMwGER9GRdGDSpyclwHwCZ5AAIgasuYKUwUOTmuA2CTPAAmiFAZM4UjQYwxBHQAHJIHIAIi2tynzuticTOI+MjGmMGlA2CTPAAj4YgM8jhTOA6UeC+6DgAleQDGImuQh22/bJe2aBCpA+CQPACsCYBZ522mcBwI4S4kHQCb7AEI9cNvNR5nCoeBEG0m0QGwyR4Aw6ith62f15nCoSNhM/sbLjoANvkDYBihMSAC3mcKw7GI6AixDoCtGgLg1IOsL2PbbwyCiQQdAEdVBCAIYnAZ234bRStCOgCOaggAqwfpdduvuIqIDoCjGgLA6kF63fY7hrtVhNIBsFVBAFg9SM/bfkeKy4PoANiqIACsHqTXbb+9IVwR0gFwVEEAWD1Ij11AdqqUQwfAJn8AWD1IzxdGNejFoKLkD4CgHiTb9uulsAijA2CTPgBsJOf5wqjWQgsBOgA26QMgqAfJtv16KSzC6AA4pA/ASBCt4gujZOgC6gBUKACsRKT4wigJSkTqAFQuAKNANIQ9XxjFCotw6QA4ZA8AG8kJFgg8FRZhdAAckgeATeYLFgi8HRdgdAAckgegFcRI8QJBuYVFdAAccgdgAKgxZVwYFS1cm1gHwCF3ANhITrBAIEGVcDkDcPJOd0fXva6uzJVOqwiZA8BGcoIFAgmqhEsYgJNXroLZ1LHRKkTiALCD34IFAhmqhEsXgOyt78zVO5aQzAEYJhzJ1RfZ6jWmaGERZQNwZSs4uqZYIhIHoFE4kqsvstu7qeiZMEUDcLILfEvmWAISB6CXCSAaFtVlTBhC/QMAzJghpGgAXrdDqNvikzgARksw3sx/zCdEG4aFDbFYazw43BBTMwDkikbHkcOfFry4fPnNQmRlLB6pA1A9pAjAtHY43r54NMnx+NMRON5bHDoA6gTgHmwLX0zq6dEbOLjjQR0AVQLwHrbDztPPvDgCavpJy00HQJEATFkC6s0kt8cfhN0AHQBVAtABascknudHQHGmA3QA1AjAFFALH03iWgCqw8qnA6BIADKgnk8SOAxiibsXoAOgRgCmsxcA13NQV6w8kgUgPKRXJdUZDuUC0MkagIJNQJeVT6oAjDNRWf0GGJRyAXgP4sMkscsgNln5ZArAT/bupqeJII7j+NBuLX2AQgErilV8wof9JZWYQj2oiWBij9wtEZMmpmfpiZ5LbySQ4AEucJBGIhLxIb45nemCtdtpabtb15n/5+jFB77dedjpeAOuCzNBuQBK4A5ScjsQPpgNvBRAAu4LMk65AN6De55qYQGcbTfQSwEMwn0BxikXwBK4vVQLq+Bsr4UpACUCWAa3m2ohD862DPBeAIcLvViRKqocQEahAJ6nevDskdSiygGoNARQAO5MAvnf/7+YBFIAXS8D8ym5XQjzZgMKQIkA1sG13wjKmI0oACUCSEPYT0lVwZXMBhSAGgFYs8BqSmYfwqbZiAJQI4DtNo+AFXBzpg0FoEYA81lwi7utZgDImY0oAEUCMHMQqjstBoDsvGlDASgSwPwyhDwvQHIseNu0oQBUCcB8gpqVXcnzH0tmExSAKgGYJdQUyzupOnurqMmmzSYoAGUCMCuwHJZPnwI7+3lw8iWgbgHcm75wI6BoAGsVnFnIH5WPDlaLsEjfA+oWgOBLTKkYgLn2HjJZ2edfywB4A/GQegHwxWBzSxumhK4BAL4bCgZgvlqC3cvcmimjbwDAYFC9AExz3ZZAKW3K6RwAfJcUDMA0X5UyOPWy8nHebEW3AO5eSIQNnIomVQzgt/Tmx1wpl1t/1e7Zr10AfAkYvOWHxRhQM4Dz0jOA32Z8qIkFKAAdA2ChK6jxhygAHQNgLG5AmKYA9AyA3YFgDFMAegbAIhBuUgCaBsBuQrhEAWgawGgUXIIC0DQAaxCIhigATQMIGuAmKQBNA7BmAdcpAF0DuAUuTAHoGsAwuBgFoGsAzAAXpAB0DcAHbpQC0DWAIXDDFICuAfhqv0oB6BpAFNwYBaBpAGPgDFoF6BrAJLhxCkDXAK6Au0wB6BrAVXAXKQBNA5iBMEoBaBrAOLhrdB5A0wDuQ5ihAPQMIGmA89GZQD0DGL0KYYYC0DKAwDiEMH0vQMsAkjEI0QAFoGEAoYiBmhn6bqB+AQTjPlgi9O1gvQIYHkvGBw2cuqLo/QDnpV8Af7ur5A0hHdA7gOgdFe8I6ojWAQyOKnhLWIc0DiB8W8V7Av+5/ySA6OWkijeFeoDnAzBi44ORqZCSdwV7gecDUPm2cC+gACgACoACoAAogG4CmHA1gEMKwM5bASTAlV0KoFj3HSAKwOKtAK73HMCzFgFACDKOArB4K4C74I5SPfj8SKZQ//tTABZvBRAHl3cngJ/1B0ApAIu3ApgEt5DqQUEawEn9VwAoAIu3AhgDV3QngHL9fWAUgMVbAbCr4PZS3XskVa0/AUgBWDwWwANwR26sAgvF+rtgKACLxwKIgKu6MQc8ARdlNRSAxWMBDEDYdWEKkK+/CIACOOWxANgQuCPXRoAbzEGh4JlILYC3MrPzujBfy3wBZwT/YHbT4A53HB8ByrZrwXs14DdAehKbDknGgLLTI0DhENw95phgDKRnEdYoDG5xx+EHwHMIA8wxF0F655NsBqLs8AOg6Pg24C2Q3l1lNn5wxV1HHwAHEG4z50yC9M7PbO5AqHaxBCi03gNAmDloGEJWao7Mzb2RyoKbYHbXIBw5NwB8LoIzBpiDRiDMSs2bxHwo9VH6aiZgQNh3ag+gUIUb74Fi4N7NynwwSYsASuDi8mMhKO459PPPQ/CNMEf5wX2flflqkhYBvJf/b12hcDcFFNpMAI0p5qwJcLlZmW8m+SQPINPi3dzY1c4LKLT5/OM+c9g0ANr+7+3FACRP5QHDKuB5zz//VcClt0AXwVVmpUzyWhpAGtxQ2222g52efv4nh6gJh5jTBsDNzUqtmdp7LA3gCbjB9vtsC3vdbwAUyrCEg8xxIQPcMS0DupkDbrW7oWvGgOVgt7Ofv/3jj2sjzAVhcCWaBXYxB3ycBZdkcncMWIryBOQbwIWTFZy6OcLccAHcMk0CupgCbJ7jfNbwEM5Uyzsdffx/lhdxZpq5YxjCdxoDut0FuMdaCk7gj2L1aH/3PD/+ws+Tg0X8EZtibvEDwNMKjQEdjwBpNNsGGrkRuTzxlyj+VlxYqa7WyTdaXVlEg/BEvXtX4gGn3wgf0zqg0zXAVpPDAMHrBvojPMWcMRIFt0SPgA4fABtNbumciqF/EiHmiAiEHD0COnoAPF4CFwva5vx9cy3k5LnAl+9oO7iTbeAchAu2vd8+SjBHxCFk3tJCwEa+BGzydtaPfptycjMIFRoEzj0ApF/az+fdQc3W+hOnvJL4mHH0eNiwAeEHDQLnHADScxAS9tvBsq/68Qd4vAVh1NnDwZW3tBI4zz//RhbCUJDVMcCt92cIepwBF2fOuIKazDsqoP0KcB01sYD9XoisyfXxOKJDHqAmm6MC2nz+X2yh6fGsS+CWTMH9bahNZ0+IjFyDpXIsmQdoNhOU/fzX51BjTDa7GWa5XwGsO3xGeOQBTv04ptWg5F/+9ZMMLMZt1sAAt9mnIaDi4BxACCVwZqn0Tu8jws0//hu5OZzyDUiG0Uza7T+HsI2e7ooZCzQxjTrLP0rfj4/fNZhNa2HtRYP59Ob2+yz+8CUDNnchLG9vpJ3yQmJjC4IvYDPG2ksOgShrKEmXAugtFqSvBOttkrWWBFFakrXhB1GYn7UTTIz7iKLGE0FGCPnV3r2jQAhDARR9fjAYJSDIKH4KkbGRt//tTR0tkmKIhfes48IFAAAAAAAAAAAAXsplYWMtNyZDIkZu6jELcxK2rBqjrMRndkUyuxFfVWqMdflfFfwVz6BIaLi2vOmr4Fk8uSKhXDzzA1VwI55ekVAvnkZjZRJgNU7bcRl80Ec8XatxrISYzRYRJicXx1kgkfOQCzcVEexGFQwAAAAAAAAAAAAAwAv8AONn30C3WSUfAAAAAElFTkSuQmCC' />
             Harshith H M
          </Heading>
          <Divider />
          <Box mt={4}>
            <Text fontSize={20}>
              A committed and motivated Software Engineer with nearly 5 years of experience in fullstack web
              development (frontend focus) majorly in ReactJs and .Net technologies. I have made an impactful
              contribution to the products that are scaled to millions of users.
            </Text>
          </Box>
          <HStack mt={4}>
            <Box onClick={() => window.open('https://www.linkedin.com/in/hmharshith/')} mr={4} cursor='pointer'>
              <svg
                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                data-supported-dps="24x24" fill="currentColor" width="35" height="35" focusable="false">
                <path d="M20.5 2h-17A1.5 1.5 0 002 3.5v17A1.5 1.5 0 003.5 22h17a1.5 1.5 0 001.5-1.5v-17A1.5 1.5 0 0020.5 2zM8 19H5v-9h3zM6.5 8.25A1.75 1.75 0 118.3 6.5a1.78 1.78 0 01-1.8 1.75zM19 19h-3v-4.74c0-1.42-.6-1.93-1.38-1.93A1.74 1.74 0 0013 14.19a.66.66 0 000 .14V19h-3v-9h2.9v1.3a3.11 3.11 0 012.7-1.4c1.55 0 3.36.86 3.36 3.66z"></path>
              </svg>
            </Box>
            <Box onClick={() => window.open('https://github.com/hmharshith')} cursor='pointer'>
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
              </svg>
            </Box>
          </HStack>
          <Box mt={[8, 12]}>
            <Text fontWeight={600}>Skill Set</Text>
            <Divider mb={4} />
            <VStack alignItems={'flex-start'}>
              <Code p={'2px'}>
                Javascript | Typescript | HTML | CSS | C#
              </Code>
              <Code p={'2px'}>
                React.js | React Native | Graphql | .Net
              </Code>
              <Code p={'2px'}>
                Hooks | Redux | Webpack | Rollup
              </Code>
              <Code p={'2px'}>
                Jest | Cypress | Nunit | Xunit
              </Code>
              <Code p={'2px'}>
                PSDS &#38; System Design
              </Code>
            </VStack>
          </Box>
          <Card mt={6}>
            <CardBody>
              <Text fontWeight={600}>
                This is a personal website and portfolio
              </Text>
              <Text>
                Built with{' '}
                <Link
                  href="https://nextjs.org"
                  target='_blank'
                  textDecoration={'underline'}
                  textUnderlineOffset={2}
                >
                  Next.js
                </Link>
                {' '}and hosted on{' '}
                <Link
                  textDecoration={'underline'}
                  textUnderlineOffset={2}
                  href="https://vercel.com" target={'_blank'}>Vercel</Link>
              </Text>
            </CardBody>
          </Card>
        </Box>
      </main>
    </>)
}

export default About;