import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Text as Typography } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Harshith HM</title>
        <meta name="description" content="Generated by Harshith HM" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Typography fontSize={"xx-large"}>
            hello
          </Typography>
        </div>
      </main>
    </>
  )
}
