import Head from 'next/head'
import Image from 'next/image'
import { Grid, GridItem, Heading, Show, Text } from '@chakra-ui/react'
import styles from '@/styles/Home.module.css'
import TypeWriter from '@/components/TypeWriter'
import { Motion, spring } from 'react-motion'
import PageHeader from '@/components/PageHeader'

export default function Home() {
  return (
    <>
      <Head>
        <title>Harshith HM</title>
        <meta name="description" content="Generated by Harshith HM" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        <PageHeader />
        <Show below='sm'>
          <Grid
            w='100%'
            h='100%'
            templateRows='repeat(1, 1fr)'
            templateColumns='repeat(1, 1fr)'
            justifyItems={'center'}
          >
            <GridItem>
              <Motion
                defaultStyle={{ translateX: -50 }}
                style={{ translateX: spring(0, { stiffness: 120, damping: 9 }) }}
              >
                {value => <Text fontSize={'large'} style={{ transform: `translateX(${value.translateX}px)` }}>
                  👋 Hello, My name is
                </Text>}
              </Motion>
              <Heading ml={'10px'}>
                <TypeWriter
                  content='Harshith HM'
                  delay={500}
                />
              </Heading>
            </GridItem>
            <GridItem mt={10}>
              <Motion
                defaultStyle={{ translateX: 100 }}
                style={{ translateX: spring(0, { stiffness: 120, damping: 9 }) }}
              >
                {value => <Image
                  src={'/freelancer.png'}
                  alt='Harshith HM'
                  width={200}
                  height={200}
                  style={{ transform: `translateX(${value.translateX}px)` }}
                />}
              </Motion>
            </GridItem>
          </Grid>
        </Show>
        <Show above='sm'>
          <Grid
            w='100%'
            h='100%'
            templateRows='repeat(1, 1fr)'
            templateColumns='repeat(8, 1fr)'
          >
            <GridItem colSpan={2} />
            <GridItem
              colSpan={2}
              mt={20}
            >
              <Motion
                defaultStyle={{ translateX: -100 }}
                style={{ translateX: spring(0, { stiffness: 120, damping: 9 }) }}
              >
                {value => <Text fontSize={'large'} style={{ transform: `translateX(${value.translateX}px)` }}>
                  👋 Hello, My name is
                </Text>}
              </Motion>
              <Heading ml={'10px'}>
                <TypeWriter
                  content='Harshith HM'
                  delay={500}
                />
              </Heading>
            </GridItem>
            <GridItem colSpan={2}>
              <Motion
                defaultStyle={{ translateX: 220 }}
                style={{ translateX: spring(0, { stiffness: 120, damping: 9 }) }}
              >
                {value => <Image
                  src={'/freelancer.png'}
                  alt='Harshith HM'
                  width={350}
                  height={350}
                  style={{ transform: `translateX(${value.translateX}px)` }}
                />}
              </Motion>
            </GridItem>
            <GridItem colSpan={2} />
          </Grid>
        </Show>
      </main>
    </>
  )
}
