import Head from "next/head"

const Projects = () => {
  return (
    <>
      <Head>
        <title>My Projects</title>
        <meta name="description" content="Generated by Harshith HM" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        hello world
      </main>
    </>)
}

export default Projects;